services:
  postgres:
    container_name: cargo_delivery_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cargo_delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: cargo_delivery_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=cargo_delivery_db;Username=postgres;Password=postgres

volumes:
  postgres-data: